# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# Set the maximum number of workers to 2 to keep memory usage low.
org.gradle.workers.max=2
kotlin.code.style=official
android.nonTransitiveRClass=true
# Run the Kotlin compiler in-process to avoid "Could not connect to Kotlin compile daemon" errors.
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx2g
android.useAndroidX=true
